/* Generated by Yosys 0.27+22 (git sha1 0f5e7c244, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1680770278298/work=/usr/local/src/conda/yosys-0.27_29_g0f5e7c244 -fdebug-prefix-map=/home/vsduser/opt/f4pga/xc7/conda/envs/xc7=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:1.1-22.10" *)
module top(clk, led);
  (* force_downto = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:18.16-18.27|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 12 13 14 16 17 18 20 21 22 24 25" *)
  wire [25:0] _00_;
  (* force_downto = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:18.16-18.27|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/arith_map.v:112.23-112.24" *)
  wire [25:0] _01_;
  (* force_downto = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:18.16-18.27|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/arith_map.v:112.26-112.27" *)
  wire [25:0] _02_;
  (* force_downto = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:18.16-18.27|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/arith_map.v:170.23-170.24" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 12 13 14 16 17 18 20 21 22 24 25 26 27" *)
  wire [27:0] _03_;
  (* force_downto = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:18.16-18.27|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/arith_map.v:168.23-168.24" *)
  (* unused_bits = "26 27" *)
  wire [27:0] _04_;
  (* CLASS = "clock" *)
  (* CLOCK_SIGNAL = "yes" *)
  (* IS_PROPAGATED = 32'd1 *)
  (* NAME = "\\$iopadmap\\$clk" *)
  (* PERIOD = "10.000000" *)
  (* SOURCE_WIRES = "\\$iopadmap\\$clk" *)
  (* WAVEFORM = "0.000000 5.000000" *)
  wire _05_;
  (* CLASS = "clock" *)
  (* CLOCK_SIGNAL = "yes" *)
  (* IS_PROPAGATED = 32'd1 *)
  (* NAME = "bufg" *)
  (* PERIOD = "10.000000" *)
  (* SOURCE_WIRES = "bufg" *)
  (* WAVEFORM = "0.000000 5.000000" *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:9.8-9.12" *)
  wire bufg;
  (* CLASS = "clock" *)
  (* CLOCK_SIGNAL = "yes" *)
  (* IS_EXPLICIT = 32'd1 *)
  (* NAME = "clk" *)
  (* PERIOD = "10.000000" *)
  (* SOURCE_WIRES = "clk" *)
  (* WAVEFORM = "0.000000 5.000000" *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:15.28-15.35" *)
  wire [25:0] counter;
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:3.18-3.21" *)
  output [3:0] led;
  wire [3:0] led;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _06_ (
    .I(counter[0]),
    .O(_01_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:18.16-18.27|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _07_ (
    .CI(1'h0),
    .CO(_00_[3:0]),
    .CYINIT(1'h0),
    .DI(4'h1),
    .O(_02_[3:0]),
    .S({ counter[3:1], _01_[0] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:18.16-18.27|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _08_ (
    .CI(_00_[3]),
    .CO(_00_[7:4]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_02_[7:4]),
    .S(counter[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:18.16-18.27|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _09_ (
    .CI(_00_[7]),
    .CO(_00_[11:8]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_02_[11:8]),
    .S(counter[11:8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:18.16-18.27|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _10_ (
    .CI(_00_[11]),
    .CO(_00_[15:12]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_02_[15:12]),
    .S(counter[15:12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:18.16-18.27|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _11_ (
    .CI(_00_[15]),
    .CO(_00_[19:16]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_02_[19:16]),
    .S(counter[19:16])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:18.16-18.27|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _12_ (
    .CI(_00_[19]),
    .CO(_00_[23:20]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_02_[23:20]),
    .S(counter[23:20])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:18.16-18.27|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _13_ (
    .CI(_00_[23]),
    .CO({ _03_[27:26], _00_[25:24] }),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O({ _04_[27:26], _02_[25:24] }),
    .S({ 2'h0, counter[25:24] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _14_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[0]),
    .Q(counter[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _15_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[1]),
    .Q(counter[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _16_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[2]),
    .Q(counter[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _17_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[3]),
    .Q(counter[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _18_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[4]),
    .Q(counter[4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _19_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[5]),
    .Q(counter[5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _20_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[6]),
    .Q(counter[6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _21_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[7]),
    .Q(counter[7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _22_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[8]),
    .Q(counter[8]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _23_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[9]),
    .Q(counter[9]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _24_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[10]),
    .Q(counter[10]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _25_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[11]),
    .Q(counter[11]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _26_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[12]),
    .Q(counter[12]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _27_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[13]),
    .Q(counter[13]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _28_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[14]),
    .Q(counter[14]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _29_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[15]),
    .Q(counter[15]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _30_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[16]),
    .Q(counter[16]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _31_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[17]),
    .Q(counter[17]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _32_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[18]),
    .Q(counter[18]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _33_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[19]),
    .Q(counter[19]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _34_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[20]),
    .Q(counter[20]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _35_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[21]),
    .Q(counter[21]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _36_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[22]),
    .Q(counter[22]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _37_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[23]),
    .Q(counter[23]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _38_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[24]),
    .Q(counter[24]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:17.3-19.6|/home/vsduser/opt/f4pga/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _39_ (
    .C(bufg),
    .CE(1'h1),
    .D(_02_[25]),
    .Q(counter[25]),
    .R(1'h0)
  );
  (* keep = 32'd1 *)
  IBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("clk:E3")
  ) _40_ (
    .I(clk),
    .O(_05_)
  );
  (* keep = 32'd1 *)
  OBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("led[0]:H5")
  ) _41_ (
    .I(counter[22]),
    .O(led[0])
  );
  (* keep = 32'd1 *)
  OBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("led[1]:J5")
  ) _42_ (
    .I(counter[23]),
    .O(led[1])
  );
  (* keep = 32'd1 *)
  OBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("led[2]:T9")
  ) _43_ (
    .I(counter[24]),
    .O(led[2])
  );
  (* keep = 32'd1 *)
  OBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("led[3]:T10")
  ) _44_ (
    .I(counter[25]),
    .O(led[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vsduser/f4pga-examples/xc7/counter_test/counter.v:10.8-13.4" *)
  BUFG bufgctrl (
    .I(_05_),
    .O(bufg)
  );
  assign _01_[25:1] = counter[25:1];
  assign _03_[25:0] = _00_;
  assign _04_[25:0] = _02_;
endmodule
