`ifndef TB_RNM_SV
`define TB_RNM_SV

`timescale 1ns/1ps
`include "../../RTL/sensor_status_native.v"
// `include "if/sensor_rnm_if.sv"
// =============================================================================
// RNM + Sensor RTL Integration Testbench
//
// Signal flow:
//
//   real temperature
//          |
//          v
//   temp_sensor_rnm
//          |
//          | real sensor_voltage
//          v
//       adc_rnm
//          |
//          | digital ADC code
//          v
//   sensor_adc_rnm
//          |
//          | temperature_tenthsC_i
//          | sensor_valid_i
//          v
//   sensor_status_native_slave
//
// The testbench also performs native-MMIO READ transactions to verify that
// the temperature generated by the RNM chain is actually visible through
// the same digital interface used by the SoC.
//
// =============================================================================
//
// IMPORTANT: SystemVerilog simulation scheduling
// =============================================================================
//
// A clock edge does NOT mean that all RTL activity happens instantaneously
// in one simulation region.
//
// For a typical:
//
//     @(posedge clk);
//
// the simulator processes events through scheduling regions.
//
// Simplified view:
//
//     Preponed
//        |
//        v
//     Active
//        |
//        |  RTL always @(posedge clk)
//        |  blocking assignments execute here
//        |
//        v
//     Inactive
//        |
//        v
//     NBA (Non-Blocking Assignment)
//        |
//        |  <= updates from sequential RTL occur here
//        |
//        v
//     Observed / Reactive / Postponed
//
// For this DUT:
//
//     temp_ff1  <= temperature_tenthsC_i;
//     temp_sync <= temp_ff1;
//
// are NON-BLOCKING assignments.
//
// Therefore, after a posedge:
//     temp_ff1  gets its new value in the NBA region
//     temp_sync gets the PREVIOUS value of temp_ff1
//
// This is intentional RTL flip-flop behavior.
//
// Consequently, the RNM input does NOT immediately appear in the
// sensor_status_native_slave output. It passes through the two flip-flop
// synchronizer stages.
//
// The testbench therefore waits sufficient clock cycles before checking
// the MMIO-visible temperature.
//
// =============================================================================
//
// Why #1 is used before/after some operations:
//
// A small delay such as:
//
//     #1;
//
// moves the testbench away from the exact clock edge and gives the DUT
// sequential logic time to complete its NBA updates.
//
// This is NOT a replacement for understanding clock-cycle latency.
// The actual verification should still be based on clock cycles.
//
// =============================================================================

module tb_rnm;

    // =========================================================================
    // Parameters
    // =========================================================================

    localparam int ADC_BITS = 12;
    localparam real VREF    = 1.8;

    // =========================================================================
    // Clock and reset
    // =========================================================================

    logic clk;
    logic resetn;

    initial begin
        clk = 1'b0;
        forever #5 clk = ~clk;
    end

    // Clock period = 10 ns
    //
    // posedge:
    //   0 ns, 10 ns, 20 ns, 30 ns, ...
    //
    // negedge:
    //   5 ns, 15 ns, 25 ns, 35 ns, ... vimp 

    // =========================================================================
    // RNM signals
    // =========================================================================

    real temperature;
    real sensor_voltage;

    logic [ADC_BITS-1:0] adc_code;

    logic [15:0] temperature_tenthsC;
    logic        sensor_valid;
    logic [31:0] status_data;


    // =========================================================================
    // Native bus signals
    // =========================================================================

    logic        mem_valid;
    logic        mem_instr;
    logic        mem_ready;
    logic [11:0] mem_addr;
    logic [31:0] mem_wdata;
    logic [3:0]  mem_wstrb;
    logic [31:0] mem_rdata;

    // =========================================================================
    // RNM interface
    // =========================================================================

    sensor_rnm_if #(
        .ADC_BITS(ADC_BITS)
    ) rnm_if (
        .clk(clk)
    );

    assign rnm_if.temperature    = temperature;
    assign rnm_if.sensor_voltage = sensor_voltage;
    assign rnm_if.adc_code       = adc_code;

    // =========================================================================
    // Temperature Sensor RNM
    // =========================================================================

    temp_sensor_rnm #(
        .V_OFFSET (0.5),
        .V_PER_DEG(0.01),
        .ENABLE_NOISE(1'b1)  // this noise i enable is suspecious.
    ) u_temp_sensor (
        .temperature   (temperature),
        .sensor_voltage(sensor_voltage)
    );

    // =========================================================================
    // ADC RNM
    // =========================================================================

    adc_rnm #(
        .ADC_BITS(ADC_BITS),
        .VREF    (VREF)
    ) u_adc (
        .analog_voltage(sensor_voltage),
        .adc_code      (adc_code)
    );

    // =========================================================================
    // ADC -> Temperature conversion RNM
    // =========================================================================

    sensor_adc_rnm #(
        .ADC_BITS (ADC_BITS),
        .VREF     (VREF),
        .V_OFFSET (0.5),
        .V_PER_DEG(0.01)
    ) u_sensor_adc (
        .adc_code           (adc_code),
        .temperature_tenthsC(temperature_tenthsC),
        .sensor_valid       (sensor_valid)
    );

    // =========================================================================
    // Existing digital sensor RTL
    // =========================================================================

    sensor_status_native_slave u_sensor_slave (
        .clk                  (clk),
        .resetn               (resetn),

        .mem_valid             (mem_valid),
        .mem_instr             (mem_instr),
        .mem_ready             (mem_ready),
        .mem_addr              (mem_addr),
        .mem_wdata             (mem_wdata),
        .mem_wstrb             (mem_wstrb),
        .mem_rdata             (mem_rdata),

        .battery_percent_i     (8'd85),
        .battery_voltage_mv_i  (16'd12000),
        .temperature_tenthsC_i(temperature_tenthsC),
        .sensor_valid_i       (sensor_valid)
    );

    // =========================================================================
    // Reset task
    // =========================================================================

    task automatic reset_dut();

        begin

            resetn = 1'b0;

            mem_valid = 1'b0;
            mem_instr = 1'b0;
            mem_addr  = 12'h000;
            mem_wdata = 32'h00000000;
            mem_wstrb = 4'b0000;

            // Synchronous reset:
            // reset is sampled ONLY at posedge clk.
            repeat (2)
                @(posedge clk);

            // The DUT reset assignments execute in the Active region,
            // while <= updates complete in the NBA region.

            #1;

            resetn = 1'b1;

            $display("");
            $display("============================================================");
            $display("RESET COMPLETE");
            $display("============================================================");

        end

    endtask

    // =========================================================================
    // Native READ task
    // =========================================================================
    //
    // Sensor register addresses:
    //
    //   0x000 -> battery percentage
    //   0x004 -> battery voltage
    //   0x008 -> temperature
    //   0x00C -> status
    //
    // Native read:
    //
    //   mem_valid = 1
    //   mem_wstrb = 0000
    //
    // The slave intentionally responds one clock cycle later.
    //
    // =========================================================================

    task automatic native_read(
        input  logic [11:0] addr,
        output logic [31:0] data
    );

        begin

            // ------------------------------------------------------------
            // Drive request BEFORE the active clock edge.
            //
            // The request is therefore stable when the DUT samples it.
            // ------------------------------------------------------------

            @(negedge clk);

            mem_valid = 1'b1;
            mem_instr = 1'b0;
            mem_addr  = addr;
            mem_wdata = 32'h00000000;
            mem_wstrb = 4'b0000;

            // ------------------------------------------------------------
            // DUT samples mem_valid at the next posedge.
            // ------------------------------------------------------------

            @(posedge clk);

            // At this point we have entered the clock event.
            //
            // The DUT's always @(posedge clk) executes in the Active region.
            // Its <= assignments are scheduled for the NBA region.
            //
            // The response becomes valid after the corresponding sequential
            // updates have taken effect.

            #1;

            // ------------------------------------------------------------
            // Wait for response.
            // ------------------------------------------------------------

            while (!mem_ready) begin
                @(posedge clk);
                #1;
            end

            data = mem_rdata;

            // ------------------------------------------------------------
            // Return bus to idle.
            // ------------------------------------------------------------

            @(negedge clk);

            mem_valid = 1'b0;
            mem_addr  = 12'h000;
            mem_wdata = 32'h00000000;
            mem_wstrb = 4'b0000;

        end

    endtask

    // =========================================================================
    // Temperature test
    // =========================================================================

    task automatic test_temperature(
        input real temp_degC
    );

        logic [31:0] read_data;
        logic signed [15:0] expected_temp;
        logic signed [15:0] actual_temp;

        begin

            // ------------------------------------------------------------
            // Change the physical/RNM temperature away from posedge.
            // ------------------------------------------------------------

            @(negedge clk);

            temperature = temp_degC;

            // RNM combinational blocks recalculate:
            //
            // temperature
            //     ->
            // sensor voltage
            //     ->
            // ADC code
            //     ->
            // temperature_tenthsC
            //
            // These are behavioral calculations and are not clocked.

            #1;

            expected_temp = $rtoi(temp_degC * 10.0);

            $display("");
            $display("------------------------------------------------------------");
            $display("RNM TEMPERATURE TEST");
            $display("------------------------------------------------------------");
            $display("Temperature input      = %0.2f C", temperature);
            $display("Sensor voltage         = %0.6f V", sensor_voltage);
            $display("ADC code               = %0d", adc_code);
            $display("Recovered temperature  = %0d tenths C",
                     $signed(temperature_tenthsC));
            $display("Sensor valid           = %b", sensor_valid);

            // ------------------------------------------------------------
            // Allow the two-flop synchronizer in the DUT to capture
            // the RNM-generated digital temperature.
            //
            // Stage 1:
            //     temp_ff1 <= temperature_tenthsC_i
            //
            // Stage 2:
            //     temp_sync <= temp_ff1
            //
            // Therefore two clock edges are required for the new value
            // to propagate through the synchronizer.
            // ------------------------------------------------------------

            repeat (3)
                @(posedge clk);

            #1;

            // ------------------------------------------------------------
            // Read temperature through the actual native MMIO interface.
            // ------------------------------------------------------------

            native_read(12'h008, read_data);

            actual_temp = $signed(read_data[15:0]);

            $display("MMIO temperature       = %0d tenths C",
                     actual_temp);

            // ------------------------------------------------------------
            // Check result.
            //
            // Because the sensor model contains noise, the recovered
            // temperature will not necessarily equal the ideal input
            // exactly.
            // ------------------------------------------------------------

            if ((actual_temp >= expected_temp - 10) &&
                (actual_temp <= expected_temp + 10)) begin

                $display("RESULT                 = PASS");

            end
            else begin

                $error("Temperature mismatch: expected approximately %0d, got %0d",
                       expected_temp,
                       actual_temp);

            end

        end

    endtask

    // =========================================================================
    // Main test
    // =========================================================================

    initial begin

        // Initialize all testbench-controlled signals.
        temperature = 25.0;

        resetn = 1'b0;

        mem_valid = 1'b0;
        mem_instr = 1'b0;
        mem_addr  = 12'h000;
        mem_wdata = 32'h00000000;
        mem_wstrb = 4'b0000;

        // ------------------------------------------------------------
        // Reset
        // ------------------------------------------------------------

        reset_dut();

        // ------------------------------------------------------------
        // Normal operating temperatures
        // ------------------------------------------------------------

        test_temperature(25.0);
        test_temperature(85.0);
        test_temperature(79.9);
        test_temperature(80.1);

        // ------------------------------------------------------------
        // Status-register test
        // ------------------------------------------------------------


        native_read(12'h00C, status_data);

        $display("");
        $display("============================================================");
        $display("STATUS REGISTER");
        $display("============================================================");
        $display("STATUS = 0x%08h", status_data);
        $display("sensor_valid = %b", status_data[0]);
        $display("battery_low  = %b", status_data[1]);
        $display("temp_alarm   = %b", status_data[2]);

        // ------------------------------------------------------------
        // Finish
        // ------------------------------------------------------------

        $display("");
        $display("============================================================");
        $display("RNM + SENSOR RTL INTEGRATION TEST COMPLETE");
        $display("============================================================");

        $finish;

    end

endmodule

`endif