`timescale 1ns / 1ps

//==============================================================================
// Module      : nn_axi_wrapper
// Project     : RISCV-VDP-SoC
//
// Description :
//   Memory-mapped TPU/NN peripheral for the native RISC-V SoC bus.
//
// Architectural boundary:
//   This module is ONLY the MMIO/register-bank boundary.
//
//       Native SoC bus
//             |
//             v
//       MMIO register bank
//             |
//             +---- payload registers
//             |
//             +---- START pulse
//             |
//             v
//       nn_axis_master
//
//   This module does NOT instantiate axis_nn.
//   This module does NOT instantiate nn.
//   This module does NOT implement AXI4-Stream.
//
// Addressing:
//   soc_mem_interconnect converts the system address into a 12-bit
//   NN-local address:
//
//       CPU address 0x0001_4010
//                 |
//                 v
//       nn_addr = 12'h010
//
//   Therefore bus_addr[7:0] is sufficient for the current register map.
//
// Payload:
//   Beat 0 = weight0
//   Beat 1 = weight1
//   Beat 2 = weight2
//   Beat 3 = weight3
//   Beat 4 = weight4
//   Beat 5 = input0
//   Beat 6 = input1 + TLAST
//
//==============================================================================

module nn_axi_wrapper #(
    parameter BASE_ADDR = 32'h0001_4000
)(
    input wire         clk,
    input wire         rst_n,

    //--------------------------------------------------------------------------
    // Native SoC memory-mapped slave interface
    //
    // IMPORTANT:
    // bus_addr is the LOCAL NN address generated by soc_mem_interconnect.
    //--------------------------------------------------------------------------
    input  wire         bus_req,
    input  wire         bus_write,
    input  wire [31:0]  bus_addr,
    input  wire [31:0]  bus_wdata,
    input  wire [3:0]   bus_strb,

    output reg          bus_ready,
    output reg  [31:0]  bus_rdata,

    //--------------------------------------------------------------------------
    // Accelerator command/payload interface
    //--------------------------------------------------------------------------
    output reg          axis_start,

    output reg [63:0]   weight0,
    output reg [63:0]   weight1,
    output reg [63:0]   weight2,
    output reg [63:0]   weight3,
    output reg [63:0]   weight4,

    output reg [63:0]   input0,
    output reg [63:0]   input1,

    //--------------------------------------------------------------------------
    // Accelerator status
    //
    // These are generated by nn_axis_master/tpu_axis_top.
    // They are NOT ports of axis_nn.
    //--------------------------------------------------------------------------
    input wire          axis_busy,
    input wire          axis_done,

    //--------------------------------------------------------------------------
    // Accelerator result registers
    //--------------------------------------------------------------------------
    input wire [63:0]   result0,
    input wire [63:0]   result1
);

    //==========================================================================
    // Register offsets inside the 4-KB TPU window
    //==========================================================================

    localparam [7:0] REG_CONTROL  = 8'h00;
    localparam [7:0] REG_STATUS   = 8'h04;

    localparam [7:0] REG_WEIGHT0_L = 8'h10;
    localparam [7:0] REG_WEIGHT0_H = 8'h14;

    localparam [7:0] REG_WEIGHT1_L = 8'h18;
    localparam [7:0] REG_WEIGHT1_H = 8'h1C;

    localparam [7:0] REG_WEIGHT2_L = 8'h20;
    localparam [7:0] REG_WEIGHT2_H = 8'h24;

    localparam [7:0] REG_WEIGHT3_L = 8'h28;
    localparam [7:0] REG_WEIGHT3_H = 8'h2C;

    localparam [7:0] REG_WEIGHT4_L = 8'h30;
    localparam [7:0] REG_WEIGHT4_H = 8'h34;

    localparam [7:0] REG_INPUT0_L = 8'h38;
    localparam [7:0] REG_INPUT0_H = 8'h3C;

    localparam [7:0] REG_INPUT1_L = 8'h40;
    localparam [7:0] REG_INPUT1_H = 8'h44;

    localparam [7:0] REG_RESULT0_L = 8'h50;
    localparam [7:0] REG_RESULT0_H = 8'h54;

    localparam [7:0] REG_RESULT1_L = 8'h58;
    localparam [7:0] REG_RESULT1_H = 8'h5C;

    //==========================================================================
    // Native bus write logic
    //
    // The native SoC data bus is 32 bits wide while the NN payload registers
    // are 64 bits wide. Therefore every 64-bit register is accessed using
    // two 32-bit transactions.
    //
    // Byte strobes are honored independently.
    //==========================================================================

    always @(posedge clk or negedge rst_n) begin

        if (!rst_n) begin

            bus_ready <= 1'b0;

            axis_start <= 1'b0;

            weight0 <= 64'd0;
            weight1 <= 64'd0;
            weight2 <= 64'd0;
            weight3 <= 64'd0;
            weight4 <= 64'd0;

            input0 <= 64'd0;
            input1 <= 64'd0;
        end

        else begin

            // Default response.
            bus_ready <= 1'b0;

            // START is deliberately a pulse.
            axis_start <= 1'b0;

            if (bus_req) begin

                // This peripheral has no variable-latency MMIO accesses.
                bus_ready <= 1'b1;

                if (bus_write) begin

                    //------------------------------------------------------------------
                    // CONTROL
                    //
                    // bit 0 = START
                    //
                    // A START command is accepted only when the accelerator is idle.
                    // This prevents software from accidentally retriggering a running
                    // transaction.
                    //------------------------------------------------------------------

                    if (bus_addr[7:0] == REG_CONTROL) begin

                        if (bus_strb[0] &&
                            bus_wdata[0] &&
                            !axis_busy) begin

                            axis_start <= 1'b1;

                        end
                    end

                    //------------------------------------------------------------------
                    // WEIGHT 0
                    //------------------------------------------------------------------

                    else if (bus_addr[7:0] == REG_WEIGHT0_L) begin

                        if (bus_strb[0]) weight0[7:0]   <= bus_wdata[7:0];
                        if (bus_strb[1]) weight0[15:8]  <= bus_wdata[15:8];
                        if (bus_strb[2]) weight0[23:16] <= bus_wdata[23:16];
                        if (bus_strb[3]) weight0[31:24] <= bus_wdata[31:24];

                    end

                    else if (bus_addr[7:0] == REG_WEIGHT0_H) begin

                        if (bus_strb[0]) weight0[39:32] <= bus_wdata[7:0];
                        if (bus_strb[1]) weight0[47:40] <= bus_wdata[15:8];
                        if (bus_strb[2]) weight0[55:48] <= bus_wdata[23:16];
                        if (bus_strb[3]) weight0[63:56] <= bus_wdata[31:24];

                    end

                    //------------------------------------------------------------------
                    // WEIGHT 1
                    //------------------------------------------------------------------

                    else if (bus_addr[7:0] == REG_WEIGHT1_L) begin

                        if (bus_strb[0]) weight1[7:0]   <= bus_wdata[7:0];
                        if (bus_strb[1]) weight1[15:8]  <= bus_wdata[15:8];
                        if (bus_strb[2]) weight1[23:16] <= bus_wdata[23:16];
                        if (bus_strb[3]) weight1[31:24] <= bus_wdata[31:24];

                    end

                    else if (bus_addr[7:0] == REG_WEIGHT1_H) begin

                        if (bus_strb[0]) weight1[39:32] <= bus_wdata[7:0];
                        if (bus_strb[1]) weight1[47:40] <= bus_wdata[15:8];
                        if (bus_strb[2]) weight1[55:48] <= bus_wdata[23:16];
                        if (bus_strb[3]) weight1[63:56] <= bus_wdata[31:24];

                    end

                    //------------------------------------------------------------------
                    // WEIGHT 2
                    //------------------------------------------------------------------

                    else if (bus_addr[7:0] == REG_WEIGHT2_L) begin

                        if (bus_strb[0]) weight2[7:0]   <= bus_wdata[7:0];
                        if (bus_strb[1]) weight2[15:8]  <= bus_wdata[15:8];
                        if (bus_strb[2]) weight2[23:16] <= bus_wdata[23:16];
                        if (bus_strb[3]) weight2[31:24] <= bus_wdata[31:24];

                    end

                    else if (bus_addr[7:0] == REG_WEIGHT2_H) begin

                        if (bus_strb[0]) weight2[39:32] <= bus_wdata[7:0];
                        if (bus_strb[1]) weight2[47:40] <= bus_wdata[15:8];
                        if (bus_strb[2]) weight2[55:48] <= bus_wdata[23:16];
                        if (bus_strb[3]) weight2[63:56] <= bus_wdata[31:24];

                    end

                    //------------------------------------------------------------------
                    // WEIGHT 3
                    //------------------------------------------------------------------

                    else if (bus_addr[7:0] == REG_WEIGHT3_L) begin

                        if (bus_strb[0]) weight3[7:0]   <= bus_wdata[7:0];
                        if (bus_strb[1]) weight3[15:8]  <= bus_wdata[15:8];
                        if (bus_strb[2]) weight3[23:16] <= bus_wdata[23:16];
                        if (bus_strb[3]) weight3[31:24] <= bus_wdata[31:24];

                    end

                    else if (bus_addr[7:0] == REG_WEIGHT3_H) begin

                        if (bus_strb[0]) weight3[39:32] <= bus_wdata[7:0];
                        if (bus_strb[1]) weight3[47:40] <= bus_wdata[15:8];
                        if (bus_strb[2]) weight3[55:48] <= bus_wdata[23:16];
                        if (bus_strb[3]) weight3[63:56] <= bus_wdata[31:24];

                    end

                    //------------------------------------------------------------------
                    // WEIGHT 4
                    //------------------------------------------------------------------

                    else if (bus_addr[7:0] == REG_WEIGHT4_L) begin

                        if (bus_strb[0]) weight4[7:0]   <= bus_wdata[7:0];
                        if (bus_strb[1]) weight4[15:8]  <= bus_wdata[15:8];
                        if (bus_strb[2]) weight4[23:16] <= bus_wdata[23:16];
                        if (bus_strb[3]) weight4[31:24] <= bus_wdata[31:24];

                    end

                    else if (bus_addr[7:0] == REG_WEIGHT4_H) begin

                        if (bus_strb[0]) weight4[39:32] <= bus_wdata[7:0];
                        if (bus_strb[1]) weight4[47:40] <= bus_wdata[15:8];
                        if (bus_strb[2]) weight4[55:48] <= bus_wdata[23:16];
                        if (bus_strb[3]) weight4[63:56] <= bus_wdata[31:24];

                    end

                    //------------------------------------------------------------------
                    // INPUT 0
                    //------------------------------------------------------------------

                    else if (bus_addr[7:0] == REG_INPUT0_L) begin

                        if (bus_strb[0]) input0[7:0]   <= bus_wdata[7:0];
                        if (bus_strb[1]) input0[15:8]  <= bus_wdata[15:8];
                        if (bus_strb[2]) input0[23:16] <= bus_wdata[23:16];
                        if (bus_strb[3]) input0[31:24] <= bus_wdata[31:24];

                    end

                    else if (bus_addr[7:0] == REG_INPUT0_H) begin

                        if (bus_strb[0]) input0[39:32] <= bus_wdata[7:0];
                        if (bus_strb[1]) input0[47:40] <= bus_wdata[15:8];
                        if (bus_strb[2]) input0[55:48] <= bus_wdata[23:16];
                        if (bus_strb[3]) input0[63:56] <= bus_wdata[31:24];

                    end

                    //------------------------------------------------------------------
                    // INPUT 1
                    //------------------------------------------------------------------

                    else if (bus_addr[7:0] == REG_INPUT1_L) begin

                        if (bus_strb[0]) input1[7:0]   <= bus_wdata[7:0];
                        if (bus_strb[1]) input1[15:8]  <= bus_wdata[15:8];
                        if (bus_strb[2]) input1[23:16] <= bus_wdata[23:16];
                        if (bus_strb[3]) input1[31:24] <= bus_wdata[31:24];

                    end

                    else if (bus_addr[7:0] == REG_INPUT1_H) begin

                        if (bus_strb[0]) input1[39:32] <= bus_wdata[7:0];
                        if (bus_strb[1]) input1[47:40] <= bus_wdata[15:8];
                        if (bus_strb[2]) input1[55:48] <= bus_wdata[23:16];
                        if (bus_strb[3]) input1[63:56] <= bus_wdata[31:24];

                    end

                end
            end
        end
    end

    //==========================================================================
    // MMIO READ DATA
    //==========================================================================

    always @(*) begin

        bus_rdata = 32'h0000_0000;

        case (bus_addr[7:0])

            REG_CONTROL:
                bus_rdata = 32'h0000_0001;

            REG_STATUS:
                begin
                    // bit 0 = BUSY
                    // bit 1 = DONE
                    bus_rdata = {30'd0, axis_done, axis_busy};
                end

            REG_WEIGHT0_L: bus_rdata = weight0[31:0];
            REG_WEIGHT0_H: bus_rdata = weight0[63:32];

            REG_WEIGHT1_L: bus_rdata = weight1[31:0];
            REG_WEIGHT1_H: bus_rdata = weight1[63:32];

            REG_WEIGHT2_L: bus_rdata = weight2[31:0];
            REG_WEIGHT2_H: bus_rdata = weight2[63:32];

            REG_WEIGHT3_L: bus_rdata = weight3[31:0];
            REG_WEIGHT3_H: bus_rdata = weight3[63:32];

            REG_WEIGHT4_L: bus_rdata = weight4[31:0];
            REG_WEIGHT4_H: bus_rdata = weight4[63:32];

            REG_INPUT0_L: bus_rdata = input0[31:0];
            REG_INPUT0_H: bus_rdata = input0[63:32];

            REG_INPUT1_L: bus_rdata = input1[31:0];
            REG_INPUT1_H: bus_rdata = input1[63:32];

            REG_RESULT0_L: bus_rdata = result0[31:0];
            REG_RESULT0_H: bus_rdata = result0[63:32];

            REG_RESULT1_L: bus_rdata = result1[31:0];
            REG_RESULT1_H: bus_rdata = result1[63:32];

            default:
                bus_rdata = 32'h0000_0000;

        endcase
    end

endmodule