#!/usr/bin/env bash

# =============================================================================
# run_questasim_sim.sh
# =============================================================================
# RISCV-VDP-SoC - Phase 5
# QuestaSim automated batch simulation runner
#
# Simulation flow:
#   1. Create work library
#   2. Compile RTL + Testbench
#   3. Compile Vivado glbl.v
#   4. Map pre-compiled Xilinx XPM library
#   5. vopt +acc -L xpm work.<TB> work.glbl -o tb_opt
#   6. vsim tb_opt
#   7. Run simulation with firmware
#
# Compatible with:
#   Vivado 2020.1
#   QuestaSim / ModelSim
#   Windows / Git Bash
# =============================================================================

set -euo pipefail


# =============================================================================
# 1. Locate script and project root
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

echo "============================================================"
echo "=== [CI Stage 2] QuestaSim Top Testbench Simulation"
echo "============================================================"
echo "Project root : $ROOT_DIR"


# =============================================================================
# 2. Locate QuestaSim tools
# =============================================================================

VSIM_BIN=""
VLOG_BIN=""
VLIB_BIN=""
VOPT_BIN=""
VMAP_BIN=""

if command -v vsim &> /dev/null; then

    VSIM_BIN="$(command -v vsim)"
    VLOG_BIN="$(command -v vlog)"
    VLIB_BIN="$(command -v vlib)"
    VOPT_BIN="$(command -v vopt)"
    VMAP_BIN="$(command -v vmap)"

elif [ -f "/c/questasim64_2024.1/win64/vsim.exe" ]; then

    VSIM_BIN="/c/questasim64_2024.1/win64/vsim.exe"
    VLOG_BIN="/c/questasim64_2024.1/win64/vlog.exe"
    VLIB_BIN="/c/questasim64_2024.1/win64/vlib.exe"
    VOPT_BIN="/c/questasim64_2024.1/win64/vopt.exe"
    VMAP_BIN="/c/questasim64_2024.1/win64/vmap.exe"

elif [ -n "${QUESTASIM_HOME:-}" ] &&
     [ -f "$QUESTASIM_HOME/win64/vsim.exe" ]; then

    VSIM_BIN="$QUESTASIM_HOME/win64/vsim.exe"
    VLOG_BIN="$QUESTASIM_HOME/win64/vlog.exe"
    VLIB_BIN="$QUESTASIM_HOME/win64/vlib.exe"
    VOPT_BIN="$QUESTASIM_HOME/win64/vopt.exe"
    VMAP_BIN="$QUESTASIM_HOME/win64/vmap.exe"

else

    echo "ERROR: QuestaSim (vsim/vlog/vlib/vopt/vmap) not found."
    exit 1

fi

echo "Using vsim : $VSIM_BIN"
echo "Using vlog : $VLOG_BIN"
echo "Using vlib : $VLIB_BIN"
echo "Using vopt : $VOPT_BIN"
echo "Using vmap : $VMAP_BIN"


# =============================================================================
# 3. Simulation configuration
# =============================================================================

TOP_TB="${SIM_TOP_TB:-tb_cpu_soc_ram_top}"
OPT_TOP="tb_opt"

SIM_TIME="${SIM_TIME:-50us}"

FW="${FIRMWARE:-$ROOT_DIR/Design_Dir/Tb/firmware.hex}"

BUILD_DIR="$ROOT_DIR/build/questasim_sim"
LOG_FILE="$BUILD_DIR/simulation.log"

RTL_DIR="$ROOT_DIR/Design_Dir/RTL"

# Vivado 2020.1
VIVADO="${VIVADO:-C:/Xilinx/Vivado/2020.1}"

GLBL="$VIVADO/data/verilog/src/glbl.v"

# Precompiled XPM library generated by Vivado compile_simlib.
#
# Override this from the command line if required:
#
#   XPM_LIB=C:/your/path/questa/xpm ./run_questasim_sim.sh
#
XPM_LIB="${XPM_LIB:-C:/projects/apb/apb.cache/compile_simlib/questa/xpm}"

TB_FILE="${SIM_TB_FILE:-$ROOT_DIR/Design_Dir/Tb/tb_soc_ram_top_with_firmw.sv}"


# =============================================================================
# 4. Display configuration
# =============================================================================

echo ""
echo "============================================================"
echo " Simulation configuration"
echo "============================================================"
echo " Testbench   : $TOP_TB"
echo " Optimized   : $OPT_TOP"
echo " Simulation  : $SIM_TIME"
echo " Firmware    : $FW"
echo " Vivado      : $VIVADO"
echo " glbl.v      : $GLBL"
echo " XPM library : $XPM_LIB"
echo " Build dir   : $BUILD_DIR"
echo " Log file    : $LOG_FILE"
echo "============================================================"


# =============================================================================
# 5. Validate required files/directories
# =============================================================================

echo ""
echo "Checking simulation files..."

if [ ! -f "$GLBL" ]; then
    echo "ERROR: Vivado glbl.v not found:"
    echo "       $GLBL"
    exit 1
fi

if [ ! -f "$TB_FILE" ]; then
    echo "ERROR: Testbench file not found:"
    echo "       $TB_FILE"
    exit 1
fi

if [ ! -f "$FW" ]; then
    echo "ERROR: Firmware file not found:"
    echo "       $FW"
    exit 1
fi

if [ ! -d "$XPM_LIB" ]; then
    echo "ERROR: Xilinx XPM library not found:"
    echo "       $XPM_LIB"
    echo ""
    echo "Generate it using Vivado compile_simlib or override XPM_LIB."
    exit 1
fi

echo "All required simulation files found."


# =============================================================================
# 6. Prepare build directory
# =============================================================================

mkdir -p "$BUILD_DIR"

cd "$BUILD_DIR"

echo ""
echo "============================================================"
echo " Cleaning previous simulation work library"
echo "============================================================"

rm -rf work
rm -f "$OPT_TOP"
rm -f transcript
rm -f vsim.wlf

echo "Creating Questa work library..."

"$VLIB_BIN" work

# Explicitly map work library
"$VMAP_BIN" work work


# =============================================================================
# 7. RTL source files
# =============================================================================

RTL_FILES=(

    "$RTL_DIR/riscv.v"
    "$RTL_DIR/riscv_wrapper.v"
    "$RTL_DIR/cpu_bus_adapter.v"
    "$RTL_DIR/soc_mem_interconnect.v"
    "$RTL_DIR/soc_ram.v"
    "$RTL_DIR/gpio_native_slave.v"
    "$RTL_DIR/rf_telemetry_native.v"
    "$RTL_DIR/sensor_status_native.v"
    "$RTL_DIR/vdp_native_slave.v"
    "$RTL_DIR/vga_timing_gen.v"
    "$RTL_DIR/cdc_reset_sync.v"
    "$RTL_DIR/pe.v"
    "$RTL_DIR/register.v"
    "$RTL_DIR/sigmoid.v"
    "$RTL_DIR/systolic.v"
    "$RTL_DIR/pe_top.v"
    "$RTL_DIR/nn.v"
    "$RTL_DIR/axis_nn.v"
    "$RTL_DIR/nn_axi_wrapper.v"
    "$RTL_DIR/nn_axis_master.v"
    "$RTL_DIR/tpu_axis_top.v"
    "$RTL_DIR/cpu_soc_ram_top.v"

)


# =============================================================================
# 8. Compile RTL + Testbench
# =============================================================================

echo ""
echo "============================================================"
echo " Compiling RTL + Testbench"
echo "============================================================"

echo " Testbench : $TB_FILE"
echo ""

set +e

"$VLOG_BIN" \
    -sv \
    -work work \
    "+incdir+$RTL_DIR" \
    "+incdir+$ROOT_DIR/Design_Dir/Tb" \
    "${RTL_FILES[@]}" \
    "$TB_FILE"

COMPILE_STATUS=$?

set -e

if [ $COMPILE_STATUS -ne 0 ]; then
    echo ""
    echo "============================================================"
    echo " ERROR: RTL/Testbench compilation failed"
    echo " Exit code: $COMPILE_STATUS"
    echo "============================================================"
    exit $COMPILE_STATUS
fi

echo ""
echo "RTL + Testbench compilation completed successfully."


# =============================================================================
# 9. Compile Xilinx glbl.v
# =============================================================================

echo ""
echo "============================================================"
echo " Compiling Xilinx glbl.v"
echo "============================================================"
echo " GLBL : $GLBL"
echo "============================================================"

set +e

"$VLOG_BIN" \
    -work work \
    "$GLBL"

GLBL_STATUS=$?

set -e

if [ $GLBL_STATUS -ne 0 ]; then
    echo ""
    echo "============================================================"
    echo " ERROR: glbl.v compilation failed"
    echo " Exit code: $GLBL_STATUS"
    echo "============================================================"
    exit $GLBL_STATUS
fi

echo ""
echo "glbl.v compilation completed successfully."


# =============================================================================
# 10. Map precompiled Xilinx XPM library
# =============================================================================

echo ""
echo "============================================================"
echo " Mapping Xilinx XPM library"
echo "============================================================"
echo " XPM library : $XPM_LIB"
echo "============================================================"

"$VMAP_BIN" xpm "$XPM_LIB"

echo ""
echo "XPM library mapped successfully."


# =============================================================================
# 11. Optimize design
# =============================================================================
#
# IMPORTANT:
#
# This is the critical difference from the previous script.
#
# We explicitly provide BOTH:
#
#     work.tb_cpu_soc_ram_top
#     work.glbl
#
# to vopt.
#
# XPM CDC models reference:
#
#     glbl.GSR
#
# Therefore glbl must be part of the optimized simulation design.
#
# This matches the known-working Makefile flow.
# =============================================================================

echo ""
echo "============================================================"
echo " Optimizing simulation design"
echo "============================================================"
echo " Testbench : work.$TOP_TB"
echo " GLBL      : work.glbl"
echo " XPM       : xpm"
echo " Output    : $OPT_TOP"
echo "============================================================"

set +e

"$VOPT_BIN" \
    +acc \
    -L xpm \
    "work.$TOP_TB" \
    work.glbl \
    -o "$OPT_TOP"

VOPT_STATUS=$?

set -e

if [ $VOPT_STATUS -ne 0 ]; then
    echo ""
    echo "============================================================"
    echo " ERROR: Questa optimization failed"
    echo " Exit code: $VOPT_STATUS"
    echo "============================================================"
    exit $VOPT_STATUS
fi

echo ""
echo "Optimization completed successfully."
echo "Optimized design : $OPT_TOP"


# =============================================================================
# 12. Run simulation
# =============================================================================

echo ""
echo "============================================================"
echo " Starting Questa simulation"
echo "============================================================"
echo " Simulation top : $OPT_TOP"
echo " Firmware       : $FW"
echo " Simulation time: $SIM_TIME"
echo " Log file       : $LOG_FILE"
echo "============================================================"

set +e

"$VSIM_BIN" \
    -c \
    "$OPT_TOP" \
    "+FIRMWARE=$FW" \
    -do "run $SIM_TIME; quit -f" \
    2>&1 | tee "$LOG_FILE"

SIM_EXIT_CODE=${PIPESTATUS[0]}

set -e


# =============================================================================
# 13. Analyze simulation result
# =============================================================================

echo ""
echo "============================================================"
echo " Analyzing simulation results"
echo "============================================================"
echo " Log : $LOG_FILE"
echo "============================================================"

if [ "$SIM_EXIT_CODE" -ne 0 ]; then

    echo ""
    echo "============================================================"
    echo " SIMULATION RESULT: FAILED"
    echo " Questa exit code: $SIM_EXIT_CODE"
    echo " See log: $LOG_FILE"
    echo "============================================================"

    exit "$SIM_EXIT_CODE"

fi


# Explicit test failure detection
if grep -iq "FAIL:" "$LOG_FILE"; then

    echo ""
    echo "============================================================"
    echo " SIMULATION RESULT: FAILED"
    echo " Explicit FAIL detected in simulation log."
    echo " See log: $LOG_FILE"
    echo "============================================================"

    exit 1

fi


# Error loading design detection
if grep -iq "Error loading design" "$LOG_FILE"; then

    echo ""
    echo "============================================================"
    echo " SIMULATION RESULT: FAILED"
    echo " 'Error loading design' detected in simulation log."
    echo " See log: $LOG_FILE"
    echo "============================================================"

    exit 1

fi


# Questa error count detection
if grep -Eq "Errors: [1-9]" "$LOG_FILE"; then

    echo ""
    echo "============================================================"
    echo " SIMULATION RESULT: FAILED"
    echo " Questa reported simulation errors."
    echo " See log: $LOG_FILE"
    echo "============================================================"

    exit 1

fi


# Successful testbench result
if grep -iq "ALL TESTS PASSED" "$LOG_FILE"; then

    echo ""
    echo "============================================================"
    echo " SUCCESS: Top Testbench ($TOP_TB) PASSED!"
    echo " Simulation time : $SIM_TIME"
    echo " Firmware        : $FW"
    echo "============================================================"

    exit 0

fi


# Simulation completed without explicit failure
echo ""
echo "============================================================"
echo " SIMULATION COMPLETED"
echo "============================================================"
echo " Testbench       : $TOP_TB"
echo " Optimized top   : $OPT_TOP"
echo " Simulation time : $SIM_TIME"
echo " Firmware        : $FW"
echo " Log             : $LOG_FILE"
echo ""
echo " No critical errors were detected."
echo "============================================================"

exit 0