`timescale 1ns/1ps

// =============================================================================
// tb_soc_ram_top.sv
//
// RISCV-VDP-SoC + TPU SYSTEM-LEVEL INTEGRATION TEST
//
// Architecture under test:
//
//      PicoRV32
//          |
//      CPU Bus Adapter
//          |
//      SoC Memory Interconnect
//       /    |      |       |       \
//     RAM  GPIO   SENSOR    RF      VDP
//                                   |
//                                NN/TPU
//                                   |
//                           nn_axi_wrapper
//                                   |
//                           nn_axis_master
//                                   |
//                              AXI4-Stream
//                                   |
//                               axis_nn
//
// TPU MMIO BASE:
//      0x0001_4000
//
// TPU AXI4-Stream transaction:
//      CPU -> wrapper -> master -> axis_nn
//
//      7 TX beats:
//          weight0
//          weight1
//          weight2
//          weight3
//          weight4
//          input0
//          input1 + TLAST
//
//      2 RX beats:
//          result0
//          result1 + TLAST
//
// This testbench:
//   1. Drives all external DUT inputs.
//   2. Connects all DUT outputs.
//   3. Verifies reset behavior.
//   4. Verifies CPU startup.
//   5. Verifies no unexpected CPU trap.
//   6. Provides sensor/RF/GPIO inputs.
//   7. Provides independent VDP pixel clock.
//   8. Monitors CPU MMIO accesses.
//   9. Detects TPU START command.
//  10. Monitors TPU busy/done.
//  11. Counts AXI4-Stream TX transfers.
//  12. Checks TX TLAST.
//  13. Counts AXI4-Stream RX transfers.
//  14. Checks RX TLAST.
//  15. Checks TPU completion.
//  16. Reports complete system-level result.
//
// IMPORTANT:
// The CPU must execute firmware which writes the TPU registers and
// writes CONTROL.START at 0x0001_4000.
//
// Therefore this TB does NOT artificially force TPU transactions.
// It verifies the real CPU-driven integration path.
//
// =============================================================================

module tb_soc_ram_top;

    // =========================================================================
    // Parameters
    // =========================================================================

    localparam ADDR_WIDTH     = 32;
    localparam DATA_WIDTH     = 32;
    localparam RAM_ADDR_WIDTH = 16;
    localparam RAM_DEPTH      = 16384;
    localparam GPIO_WIDTH     = 32;

    // -------------------------------------------------------------------------
    // TPU configuration
    // -------------------------------------------------------------------------

    localparam [31:0] NN_BASE_ADDR = 32'h0001_4000;

    localparam integer EXPECTED_TX_BEATS = 7;
    localparam integer EXPECTED_RX_BEATS = 2;

    // -------------------------------------------------------------------------
    // Expected result values.
    //
    // These must match the values generated by the currently connected
    // axis_nn test configuration.
    // -------------------------------------------------------------------------

    localparam [63:0] EXPECTED_RESULT0 =
                        64'hDEAD_BEEF_CAFE_F00D;

    localparam [63:0] EXPECTED_RESULT1 =
                        64'h1234_5678_9ABC_DEF0;


    // =========================================================================
    // System clock / reset
    // =========================================================================

    reg clk;
    reg resetn;


    // =========================================================================
    // VDP pixel clock
    //
    // Independent from CPU/system clock.
    // 25 MHz equivalent pixel clock for smoke testing.
    // =========================================================================

    reg pixel_clk;


    // =========================================================================
    // Sensor inputs
    // =========================================================================

    reg [7:0]  battery_percent;
    reg [15:0] battery_voltage;
    reg [15:0] temperature;
    reg        sensor_valid;


    // =========================================================================
    // RF telemetry inputs
    // =========================================================================

    reg [7:0] rssi_dbm;
    reg       link_up;
    reg       link_error;
    reg       carrier_detect;


    // =========================================================================
    // GPIO input
    // =========================================================================

    reg [GPIO_WIDTH-1:0] gpio_in;


    // =========================================================================
    // DUT outputs
    // =========================================================================

    wire                    rf_enable_o;

    wire [GPIO_WIDTH-1:0]   gpio_out;
    wire [GPIO_WIDTH-1:0]   gpio_oe;

    wire                    hsync_o;
    wire                    vsync_o;

    wire [11:0]             pixel_x_o;
    wire [11:0]             pixel_y_o;

    wire [3:0]              rgb_r_o;
    wire [3:0]              rgb_g_o;
    wire [3:0]              rgb_b_o;

    wire                    trap;


    // =========================================================================
    // Error counter
    // =========================================================================

    integer errors;


    // =========================================================================
    // TPU verification counters
    // =========================================================================

    integer tx_count;
    integer rx_count;

    reg tpu_start_seen;
    reg tpu_busy_seen;
    reg tpu_done_seen;

    reg tpu_tx_tlast_seen;
    reg tpu_rx_tlast_seen;

    reg tpu_result0_seen;
    reg tpu_result1_seen;

    reg tpu_test_active;


    // =========================================================================
    // DUT
    // =========================================================================

    cpu_soc_ram_top #(
        .ADDR_WIDTH     (ADDR_WIDTH),
        .DATA_WIDTH     (DATA_WIDTH),
        .RAM_ADDR_WIDTH (RAM_ADDR_WIDTH),
        .RAM_DEPTH      (RAM_DEPTH),
        .GPIO_WIDTH     (GPIO_WIDTH)
    ) dut (

        // ---------------------------------------------------------------------
        // System clock/reset
        // ---------------------------------------------------------------------

        .clk                   (clk),
        .resetn                (resetn),

        // ---------------------------------------------------------------------
        // Sensor
        // ---------------------------------------------------------------------

        .battery_percent_i     (battery_percent),
        .battery_voltage_mv_i  (battery_voltage),
        .temperature_tenthsC_i (temperature),
        .sensor_valid_i        (sensor_valid),

        // ---------------------------------------------------------------------
        // RF
        // ---------------------------------------------------------------------

        .rssi_dbm_i            (rssi_dbm),
        .link_up_i             (link_up),
        .link_error_i          (link_error),
        .carrier_detect_i      (carrier_detect),

        .rf_enable_o           (rf_enable_o),

        // ---------------------------------------------------------------------
        // GPIO
        // ---------------------------------------------------------------------

        .gpio_out              (gpio_out),
        .gpio_oe               (gpio_oe),
        .gpio_in               (gpio_in),

        // ---------------------------------------------------------------------
        // VDP / VGA
        // ---------------------------------------------------------------------

        .pixel_clk             (pixel_clk),

        .hsync_o               (hsync_o),
        .vsync_o               (vsync_o),

        .pixel_x_o             (pixel_x_o),
        .pixel_y_o             (pixel_y_o),

        .rgb_r_o               (rgb_r_o),
        .rgb_g_o               (rgb_g_o),
        .rgb_b_o               (rgb_b_o),

        // ---------------------------------------------------------------------
        // CPU status
        // ---------------------------------------------------------------------

        .trap                  (trap)
    );


    // =========================================================================
    // System clock
    //
    // 100 MHz
    // Period = 10 ns
    // =========================================================================

    initial begin
        clk = 1'b0;

        forever #5 clk = ~clk;
    end


    // =========================================================================
    // Pixel clock
    //
    // 25 MHz
    // Period = 40 ns
    // =========================================================================

    initial begin
        pixel_clk = 1'b0;

        forever #20 pixel_clk = ~pixel_clk;
    end


    // =========================================================================
    // CPU BUS MONITOR
    //
    // Monitors the adapter/interconnect side of the CPU.
    //
    // This is particularly useful for confirming that firmware actually
    // reaches the TPU MMIO region.
    // =========================================================================

    always @(posedge clk) begin

        if (resetn) begin

            if (dut.m_valid && !dut.m_write) begin

                $display(
                    "CPU READ : addr=%h ready=%b rdata=%h",
                    dut.m_addr,
                    dut.m_ready,
                    dut.m_rdata
                );

                if (dut.m_addr == 32'h0001_2000)
                    $display("***** SENSOR READ FOUND *****");

                if ((dut.m_addr & 32'hFFFF_F000) == NN_BASE_ADDR) begin
                    $display(
                        "***** TPU MMIO READ ***** addr=%h rdata=%h",
                        dut.m_addr,
                        dut.m_rdata
                    );
                end
            end


            if (dut.m_valid && dut.m_write) begin

                $display(
                    "CPU WRITE: addr=%h wdata=%h strb=%b",
                    dut.m_addr,
                    dut.m_wdata,
                    dut.m_strb
                );

                if ((dut.m_addr & 32'hFFFF_F000) == NN_BASE_ADDR) begin

                    $display(
                        "***** TPU MMIO WRITE ***** addr=%h wdata=%h strb=%b",
                        dut.m_addr,
                        dut.m_wdata,
                        dut.m_strb
                    );

                end
            end

        end

    end


    // =========================================================================
    // TPU CONTROL / STATUS MONITOR
    //
    // These signals exist inside cpu_soc_ram_top after TPU integration.
    //
    // Hierarchical references are intentional here:
    // this is a verification testbench, not synthesizable RTL.
    // =========================================================================

    always @(posedge clk) begin

        if (resetn) begin

            // -----------------------------------------------------------------
            // START pulse
            // -----------------------------------------------------------------

            if (dut.axis_start) begin

                if (!tpu_start_seen) begin

                    $display("");
                    $display("------------------------------------------------------");
                    $display("TPU START DETECTED");
                    $display("------------------------------------------------------");

                    tpu_start_seen = 1'b1;
                    tpu_test_active = 1'b1;

                end

            end


            // -----------------------------------------------------------------
            // BUSY
            // -----------------------------------------------------------------

            if (dut.axis_busy) begin

                if (!tpu_busy_seen) begin

                    $display("PASS: TPU axis_busy asserted");

                    tpu_busy_seen = 1'b1;

                end

            end


            // -----------------------------------------------------------------
            // DONE
            // -----------------------------------------------------------------

            if (dut.axis_done) begin

                if (!tpu_done_seen) begin

                    $display("PASS: TPU axis_done asserted");

                    tpu_done_seen = 1'b1;

                end

            end

        end

    end


    // =========================================================================
    // AXI4-STREAM TX MONITOR
    //
    // nn_axis_master -> axis_nn
    //
    // Transfer occurs only when:
    //
    //      TVALID && TREADY
    //
    // Expected:
    //
    //      7 transfers
    //      TLAST only on beat 6
    // =========================================================================

    always @(posedge clk) begin

        if (resetn) begin

            if (dut.nn_m_axis_tvalid &&
                dut.nn_m_axis_tready) begin

                tx_count = tx_count + 1;

                $display(
                    "TPU AXIS TX: beat=%0d data=%h tlast=%b",
                    tx_count,
                    dut.nn_m_axis_tdata,
                    dut.nn_m_axis_tlast
                );

                // -------------------------------------------------------------
                // TLAST check
                // -------------------------------------------------------------

                if (tx_count == EXPECTED_TX_BEATS) begin

                    if (dut.nn_m_axis_tlast) begin

                        $display(
                            "PASS: TPU TX TLAST asserted on final beat"
                        );

                        tpu_tx_tlast_seen = 1'b1;

                    end
                    else begin

                        $display(
                            "FAIL: TPU TX final beat missing TLAST"
                        );

                        errors = errors + 1;

                    end

                end
                else begin

                    if (dut.nn_m_axis_tlast) begin

                        $display(
                            "FAIL: TPU TX TLAST asserted early on beat %0d",
                            tx_count
                        );

                        errors = errors + 1;

                    end

                end

            end

        end

    end


    // =========================================================================
    // AXI4-STREAM RX MONITOR
    //
    // axis_nn -> nn_axis_master
    //
    // Expected:
    //
    //      2 transfers
    //      result0 = DEAD_BEEF_CAFE_F00D
    //      result1 = 1234_5678_9ABC_DEF0
    //      TLAST only on second beat
    // =========================================================================

    always @(posedge clk) begin

        if (resetn) begin

            if (dut.nn_s_axis_tvalid &&
                dut.nn_s_axis_tready) begin

                rx_count = rx_count + 1;

                $display(
                    "TPU AXIS RX: beat=%0d data=%h tlast=%b",
                    rx_count,
                    dut.nn_s_axis_tdata,
                    dut.nn_s_axis_tlast
                );


                // -------------------------------------------------------------
                // First result
                // -------------------------------------------------------------

                if (rx_count == 1) begin

                    if (dut.nn_s_axis_tdata == EXPECTED_RESULT0) begin

                        $display(
                            "PASS: TPU result0 AXIS data correct"
                        );

                        tpu_result0_seen = 1'b1;

                    end
                    else begin

                        $display(
                            "FAIL: TPU result0 mismatch: expected=%h actual=%h",
                            EXPECTED_RESULT0,
                            dut.nn_s_axis_tdata
                        );

                        errors = errors + 1;

                    end


                    if (dut.nn_s_axis_tlast) begin

                        $display(
                            "FAIL: TPU RX TLAST asserted too early"
                        );

                        errors = errors + 1;

                    end

                end


                // -------------------------------------------------------------
                // Second result
                // -------------------------------------------------------------

                if (rx_count == EXPECTED_RX_BEATS) begin

                    if (dut.nn_s_axis_tdata == EXPECTED_RESULT1) begin

                        $display(
                            "PASS: TPU result1 AXIS data correct"
                        );

                        tpu_result1_seen = 1'b1;

                    end
                    else begin

                        $display(
                            "FAIL: TPU result1 mismatch: expected=%h actual=%h",
                            EXPECTED_RESULT1,
                            dut.nn_s_axis_tdata
                        );

                        errors = errors + 1;

                    end


                    if (dut.nn_s_axis_tlast) begin

                        $display(
                            "PASS: TPU RX TLAST asserted on final beat"
                        );

                        tpu_rx_tlast_seen = 1'b1;

                    end
                    else begin

                        $display(
                            "FAIL: TPU RX final beat missing TLAST"
                        );

                        errors = errors + 1;

                    end

                end

            end

        end

    end


    // =========================================================================
    // Main test
    // =========================================================================

    initial begin

        // ---------------------------------------------------------------------
        // Initialize verification state
        // ---------------------------------------------------------------------

        errors = 0;

        tx_count = 0;
        rx_count = 0;

        tpu_start_seen    = 1'b0;
        tpu_busy_seen     = 1'b0;
        tpu_done_seen     = 1'b0;

        tpu_tx_tlast_seen = 1'b0;
        tpu_rx_tlast_seen = 1'b0;

        tpu_result0_seen  = 1'b0;
        tpu_result1_seen  = 1'b0;

        tpu_test_active   = 1'b0;


        // =====================================================================
        // Initial conditions
        // =====================================================================

        resetn = 1'b0;

        // Sensor
        battery_percent = 8'd67;
        battery_voltage = 16'd3700;
        temperature     = 16'sd235;
        sensor_valid    = 1'b1;

        // RF
        rssi_dbm       = 8'd200;
        link_up        = 1'b1;
        link_error     = 1'b0;
        carrier_detect = 1'b1;

        // GPIO
        gpio_in = 32'hA5A5_5A5A;


        $display("");
        $display("======================================================");
        $display("       TB_CPU_SOC_RAM_TOP");
        $display("       RISCV-VDP-SoC + TPU INTEGRATION TEST");
        $display("======================================================");
        $display("");
        $display("TPU BASE ADDRESS : %h", NN_BASE_ADDR);
        $display("EXPECTED TX BEATS: %0d", EXPECTED_TX_BEATS);
        $display("EXPECTED RX BEATS: %0d", EXPECTED_RX_BEATS);
        $display("");


        // =====================================================================
        // Reset
        // =====================================================================

        $display("INFO: Applying reset...");

        repeat (5) @(posedge clk);


        // ---------------------------------------------------------------------
        // Trap must remain low during reset
        // ---------------------------------------------------------------------

        if (trap === 1'b0) begin

            $display("PASS: trap low during reset");

        end
        else begin

            $display("FAIL: trap asserted during reset");

            errors = errors + 1;

        end


        // ---------------------------------------------------------------------
        // TPU must be idle during reset
        // ---------------------------------------------------------------------

        if (dut.axis_busy === 1'b0) begin

            $display("PASS: TPU busy low during reset");

        end
        else begin

            $display("FAIL: TPU busy asserted during reset");

            errors = errors + 1;

        end


        // =====================================================================
        // Release reset
        // =====================================================================

        resetn = 1'b1;

        $display("INFO: reset released");


        // =====================================================================
        // CPU startup
        // =====================================================================

        repeat (20) @(posedge clk);


        if (trap === 1'b0) begin

            $display("PASS: trap remains low after CPU startup");

        end
        else begin

            $display("FAIL: trap asserted after CPU startup");

            errors = errors + 1;

        end


        // =====================================================================
        // Check GPIO input connection
        // =====================================================================

        $display("");
        $display("INFO: GPIO input = %h", gpio_in);


        // =====================================================================
        // Check RF input configuration
        // =====================================================================

        $display("INFO: RF inputs:");
        $display("      RSSI           = %0d", rssi_dbm);
        $display("      link_up        = %b", link_up);
        $display("      link_error     = %b", link_error);
        $display("      carrier_detect = %b", carrier_detect);


        // =====================================================================
        // Check sensor configuration
        // =====================================================================

        $display("");
        $display("INFO: Sensor inputs:");
        $display("      battery_percent = %0d", battery_percent);
        $display("      battery_voltage = %0d mV", battery_voltage);
        $display("      temperature     = %0d tenths C", temperature);
        $display("      sensor_valid    = %b", sensor_valid);


        // =====================================================================
        // Allow CPU to execute.
        //
        // Firmware should eventually:
        //
        //   1. Write weight0..weight4
        //   2. Write input0/input1
        //   3. Write CONTROL.START
        //
        // TPU monitoring begins immediately.
        // =====================================================================

        $display("");
        $display("INFO: Waiting for CPU firmware to access TPU...");
        $display("INFO: TPU MMIO region = 0x0001_4000 - 0x0001_4FFF");
        $display("");

        repeat (200) @(posedge clk);


        // =====================================================================
        // TPU START check
        // =====================================================================

        if (tpu_start_seen) begin

            $display("PASS: CPU firmware issued TPU START");

        end
        else begin

            $display("FAIL: TPU START was not detected");
            $display("      Check firmware MMIO writes to 0x0001_4000");

            errors = errors + 1;

        end


        // =====================================================================
        // TPU AXI4-Stream TX count
        // =====================================================================

        if (tx_count == EXPECTED_TX_BEATS) begin

            $display(
                "PASS: TPU transmitted %0d AXIS beats",
                tx_count
            );

        end
        else begin

            $display(
                "FAIL: TPU TX beat count: expected=%0d actual=%0d",
                EXPECTED_TX_BEATS,
                tx_count
            );

            errors = errors + 1;

        end


        // =====================================================================
        // TPU TX TLAST
        // =====================================================================

        if (tpu_tx_tlast_seen) begin

            $display("PASS: TPU TX packet TLAST correct");

        end
        else begin

            $display("FAIL: TPU TX packet TLAST incorrect");

            errors = errors + 1;

        end


        // =====================================================================
        // TPU RX count
        // =====================================================================

        if (rx_count == EXPECTED_RX_BEATS) begin

            $display(
                "PASS: TPU received %0d AXIS result beats",
                rx_count
            );

        end
        else begin

            $display(
                "FAIL: TPU RX beat count: expected=%0d actual=%0d",
                EXPECTED_RX_BEATS,
                rx_count
            );

            errors = errors + 1;

        end


        // =====================================================================
        // TPU RX TLAST
        // =====================================================================

        if (tpu_rx_tlast_seen) begin

            $display("PASS: TPU RX packet TLAST correct");

        end
        else begin

            $display("FAIL: TPU RX packet TLAST incorrect");

            errors = errors + 1;

        end


        // =====================================================================
        // Result checks
        // =====================================================================

        if (tpu_result0_seen) begin

            $display("PASS: TPU result0 correct");

        end
        else begin

            $display("FAIL: TPU result0 incorrect");

            errors = errors + 1;

        end


        if (tpu_result1_seen) begin

            $display("PASS: TPU result1 correct");

        end
        else begin

            $display("FAIL: TPU result1 incorrect");

            errors = errors + 1;

        end


        // =====================================================================
        // TPU DONE check
        // =====================================================================

        if (tpu_done_seen) begin

            $display("PASS: TPU transaction completed");

        end
        else begin

            $display("FAIL: TPU DONE was not detected");

            errors = errors + 1;

        end


        // =====================================================================
        // Extended system execution
        // =====================================================================

        repeat (50) @(posedge clk);


        // =====================================================================
        // Trap check
        // =====================================================================

        if (trap === 1'b0) begin

            $display(
                "PASS: CPU/system remains running without trap"
            );

        end
        else begin

            $display(
                "FAIL: trap asserted during extended execution"
            );

            errors = errors + 1;

        end


        // =====================================================================
        // Change sensor inputs
        // =====================================================================

        battery_percent = 8'd10;
        battery_voltage = 16'd3300;
        temperature     = 16'sd801;
        sensor_valid    = 1'b1;

        repeat (10) @(posedge clk);

        $display("");
        $display("INFO: Sensor inputs changed:");
        $display("      battery_percent = %0d", battery_percent);
        $display("      battery_voltage = %0d mV", battery_voltage);
        $display("      temperature     = %0d tenths C", temperature);
        $display("      sensor_valid    = %b", sensor_valid);


        // =====================================================================
        // Change RF inputs
        // =====================================================================

        rssi_dbm       = 8'd180;
        link_up        = 1'b0;
        link_error     = 1'b1;
        carrier_detect = 1'b0;

        repeat (10) @(posedge clk);

        $display("");
        $display("INFO: RF inputs changed:");
        $display("      RSSI           = %0d", rssi_dbm);
        $display("      link_up        = %b", link_up);
        $display("      link_error     = %b", link_error);
        $display("      carrier_detect = %b", carrier_detect);


        // =====================================================================
        // Change GPIO inputs
        // =====================================================================

        gpio_in = 32'h1234_5678;

        repeat (10) @(posedge clk);

        $display("");
        $display("INFO: GPIO input changed = %h", gpio_in);


        // =====================================================================
        // Final trap check
        // =====================================================================

        repeat (20) @(posedge clk);

        if (trap === 1'b0) begin

            $display(
                "PASS: system remains stable after input changes"
            );

        end
        else begin

            $display(
                "FAIL: trap asserted after input changes"
            );

            errors = errors + 1;

        end


        // =====================================================================
        // Final TPU summary
        // =====================================================================

        $display("");
        $display("======================================================");
        $display("                 TPU TEST SUMMARY");
        $display("======================================================");

        $display("START detected       : %b", tpu_start_seen);
        $display("BUSY detected        : %b", tpu_busy_seen);
        $display("DONE detected        : %b", tpu_done_seen);

        $display("TX beats             : %0d / %0d",
                 tx_count, EXPECTED_TX_BEATS);

        $display("TX TLAST             : %b",
                 tpu_tx_tlast_seen);

        $display("RX beats             : %0d / %0d",
                 rx_count, EXPECTED_RX_BEATS);

        $display("RX TLAST             : %b",
                 tpu_rx_tlast_seen);

        $display("Result0 correct      : %b",
                 tpu_result0_seen);

        $display("Result1 correct      : %b",
                 tpu_result1_seen);

        $display("======================================================");


        // =====================================================================
        // Final result
        // =====================================================================

        $display("");
        $display("======================================================");

        if (errors == 0) begin

            $display(
                "TB_CPU_SOC_RAM_TOP + TPU: ALL TESTS PASSED"
            );

        end
        else begin

            $display(
                "TB_CPU_SOC_RAM_TOP + TPU: %0d TEST(S) FAILED",
                errors
            );

        end

        $display("======================================================");
        $display("");


        // ---------------------------------------------------------------------
        // Finish simulation.
        // ---------------------------------------------------------------------

        // $finish;

    end

endmodule