`ifndef SOC_TPU_SCOREBOARD_SV
`define SOC_TPU_SCOREBOARD_SV

`timescale 1ns/1ps

import uvm_pkg::*;
`include "uvm_macros.svh"

// =============================================================================
// RISCV-VDP-SoC
// TPU UVM Scoreboard
// =============================================================================
//
// PURPOSE
// -------
// This scoreboard verifies the software-visible behavior of the integrated TPU
// through the existing 32-bit native CPU bus.
//
// The scoreboard receives completed bus transactions from soc_monitor:
//
//     soc_monitor
//          |
//          | analysis_port
//          v
//     soc_tpu_scoreboard
//          |
//          v
//     TPU reference model
//          |
//          v
//     Expected RESULT0 / RESULT1
//
// The scoreboard does NOT inspect PicoRV32 internal signals directly.
//
// Instead, it observes the same native-bus transactions generated by the CPU.
// This makes the checking representative of the actual CPU-to-TPU software
// interface.
//
// =============================================================================
// TPU BASE ADDRESS
// =============================================================================
//
//     0x0001_4000
//
// Register map:
//
//     CONTROL  0x00       START bit 0
//     STATUS   0x04       BUSY bit 0, DONE bit 1
//
//     W0       0x10 / 0x14
//     W1       0x18 / 0x1C
//     W2       0x20 / 0x24
//     W3       0x28 / 0x2C
//     W4       0x30 / 0x34
//
//     INPUT0   0x38 / 0x3C
//     INPUT1   0x40 / 0x44
//
//     RESULT0  0x50 / 0x54
//     RESULT1  0x58 / 0x5C
//
// Each 64-bit register is accessed through two 32-bit native-bus transfers.
//
// =============================================================================
// REFERENCE MODEL INTERFACE
// =============================================================================
//
// The scoreboard expects the C reference model to provide a DPI-C interface:
//
//     tpu_ref_init()
//     tpu_ref_write64()
//     tpu_ref_start()
//     tpu_ref_read64()
//
// If your current C reference model uses different DPI names, ONLY the
// declarations/calls in the DPI section need to be changed.
//
// The reference model is intentionally treated as a black-box functional model.
// The scoreboard does not reproduce the TPU PE architecture.
//
// =============================================================================


class soc_tpu_scoreboard extends uvm_scoreboard;

    `uvm_component_utils(soc_tpu_scoreboard)


    // =========================================================================
    // Analysis implementation
    // =========================================================================
    //
    // soc_monitor publishes soc_sequence_item transactions through:
    //
    //     analysis_port
    //
    // The scoreboard receives those transactions through write().
    //
    // =========================================================================

    uvm_analysis_imp #(soc_sequence_item, soc_tpu_scoreboard) analysis_imp;


    // =========================================================================
    // TPU address definitions
    // =========================================================================

    localparam bit [31:0] TPU_BASE = 32'h0001_4000;

    // -------------------------------------------------------------------------
    // Control / status registers
    // -------------------------------------------------------------------------

    localparam bit [31:0] TPU_CONTROL = TPU_BASE + 32'h00;
    localparam bit [31:0] TPU_STATUS  = TPU_BASE + 32'h04;

    // -------------------------------------------------------------------------
    // Weight registers
    // -------------------------------------------------------------------------

    localparam bit [31:0] TPU_W0_LO = TPU_BASE + 32'h10;
    localparam bit [31:0] TPU_W0_HI = TPU_BASE + 32'h14;

    localparam bit [31:0] TPU_W1_LO = TPU_BASE + 32'h18;
    localparam bit [31:0] TPU_W1_HI = TPU_BASE + 32'h1C;

    localparam bit [31:0] TPU_W2_LO = TPU_BASE + 32'h20;
    localparam bit [31:0] TPU_W2_HI = TPU_BASE + 32'h24;

    localparam bit [31:0] TPU_W3_LO = TPU_BASE + 32'h28;
    localparam bit [31:0] TPU_W3_HI = TPU_BASE + 32'h2C;

    localparam bit [31:0] TPU_W4_LO = TPU_BASE + 32'h30;
    localparam bit [31:0] TPU_W4_HI = TPU_BASE + 32'h34;

    // -------------------------------------------------------------------------
    // Input registers
    // -------------------------------------------------------------------------

    localparam bit [31:0] TPU_INPUT0_LO = TPU_BASE + 32'h38;
    localparam bit [31:0] TPU_INPUT0_HI = TPU_BASE + 32'h3C;

    localparam bit [31:0] TPU_INPUT1_LO = TPU_BASE + 32'h40;
    localparam bit [31:0] TPU_INPUT1_HI = TPU_BASE + 32'h44;

    // -------------------------------------------------------------------------
    // Result registers
    // -------------------------------------------------------------------------

    localparam bit [31:0] TPU_RESULT0_LO = TPU_BASE + 32'h50;
    localparam bit [31:0] TPU_RESULT0_HI = TPU_BASE + 32'h54;

    localparam bit [31:0] TPU_RESULT1_LO = TPU_BASE + 32'h58;
    localparam bit [31:0] TPU_RESULT1_HI = TPU_BASE + 32'h5C;


    // =========================================================================
    // Captured 64-bit TPU configuration
    // =========================================================================
    //
    // The native bus is 32 bits wide.
    //
    // Therefore every 64-bit TPU register is reconstructed from:
    //
    //     LOW  32 bits
    //     HIGH 32 bits
    //
    // Example:
    //
    //     W0 = {W0_HI, W0_LO}
    //
    // =========================================================================

    bit [63:0] weight [0:4];

    bit [63:0] input0;
    bit [63:0] input1;


    // =========================================================================
    // Expected results generated by the reference model
    // =========================================================================

    bit [63:0] expected_result0;
    bit [63:0] expected_result1;


    // =========================================================================
    // Valid flags
    // =========================================================================
    //
    // These flags prevent the scoreboard from running the reference model
    // before all required 64-bit operands have been captured.
    //
    // =========================================================================

    bit w0_lo_valid;
    bit w0_hi_valid;

    bit w1_lo_valid;
    bit w1_hi_valid;

    bit w2_lo_valid;
    bit w2_hi_valid;

    bit w3_lo_valid;
    bit w3_hi_valid;

    bit w4_lo_valid;
    bit w4_hi_valid;

    bit input0_lo_valid;
    bit input0_hi_valid;

    bit input1_lo_valid;
    bit input1_hi_valid;


    // =========================================================================
    // Reference-model state
    // =========================================================================

    bit reference_model_valid;

    bit start_seen;

    bit result0_lo_checked;
    bit result0_hi_checked;

    bit result1_lo_checked;
    bit result1_hi_checked;


    // =========================================================================
    // Statistics
    // =========================================================================

    int unsigned tpu_write_count;
    int unsigned tpu_read_count;

    int unsigned result_compare_count;
    int unsigned result_error_count;

    int unsigned start_count;


    // =========================================================================
    // Constructor
    // =========================================================================

    function new(
        string name = "soc_tpu_scoreboard",
        uvm_component parent = null
    );

        super.new(name, parent);

        analysis_imp = new("analysis_imp", this);

        reference_model_valid = 1'b0;
        start_seen            = 1'b0;

        tpu_write_count       = 0;
        tpu_read_count        = 0;

        result_compare_count  = 0;
        result_error_count    = 0;
        start_count           = 0;

        clear_capture_state();

    endfunction


    // =========================================================================
    // Build phase
    // =========================================================================

    virtual function void build_phase(uvm_phase phase);

        super.build_phase(phase);

        `uvm_info(
            "TPU_SCB",
            "TPU scoreboard constructed",
            UVM_LOW
        )

    endfunction


    // =========================================================================
    // End-of-elaboration information
    // =========================================================================

    virtual function void end_of_elaboration_phase(uvm_phase phase);

        super.end_of_elaboration_phase(phase);

        `uvm_info(
            "TPU_SCB",
            "TPU scoreboard connected to native-bus monitor",
            UVM_LOW
        )

    endfunction


    // =========================================================================
    // Main analysis callback
    // =========================================================================
    //
    // Every completed native-bus transaction from soc_monitor arrives here.
    //
    // Non-TPU accesses are ignored.
    //
    // TPU accesses are decoded according to:
    //
    //     write = 1  -> configuration/control
    //     write = 0  -> status/result read
    //
    // =========================================================================

    virtual function void write(soc_sequence_item tr);

        if (tr == null) begin

            `uvm_error(
                "TPU_SCB",
                "Received null transaction"
            )

            return;

        end


        // ---------------------------------------------------------------------
        // Ignore accesses belonging to RAM/GPIO/RF/SENSOR/VDP.
        // ---------------------------------------------------------------------

        if (tr.target != "TPU")
            return;


        // ---------------------------------------------------------------------
        // TPU transaction statistics
        // ---------------------------------------------------------------------

        if (tr.write)
            tpu_write_count++;
        else
            tpu_read_count++;


        // ---------------------------------------------------------------------
        // Decode transaction type
        // ---------------------------------------------------------------------

        if (tr.write)
            process_tpu_write(tr);
        else
            process_tpu_read(tr);

    endfunction


    // =========================================================================
    // Process TPU write
    // =========================================================================
    //
    // Captures:
    //
    //     W0-W4
    //     INPUT0
    //     INPUT1
    //     CONTROL.START
    //
    // =========================================================================

    virtual function void process_tpu_write(soc_sequence_item tr);

        case (tr.addr)

            // =================================================================
            // W0
            // =================================================================

            TPU_W0_LO: begin

                weight[0][31:0] = tr.wdata;

                w0_lo_valid = 1'b1;

                `uvm_info(
                    "TPU_WRITE",
                    $sformatf(
                        "W0_LO = 0x%08h",
                        tr.wdata
                    ),
                    UVM_MEDIUM
                )

            end


            TPU_W0_HI: begin

                weight[0][63:32] = tr.wdata;

                w0_hi_valid = 1'b1;

                `uvm_info(
                    "TPU_WRITE",
                    $sformatf(
                        "W0_HI = 0x%08h",
                        tr.wdata
                    ),
                    UVM_MEDIUM
                )

            end


            // =================================================================
            // W1
            // =================================================================

            TPU_W1_LO: begin

                weight[1][31:0] = tr.wdata;

                w1_lo_valid = 1'b1;

                `uvm_info(
                    "TPU_WRITE",
                    $sformatf(
                        "W1_LO = 0x%08h",
                        tr.wdata
                    ),
                    UVM_MEDIUM
                )

            end


            TPU_W1_HI: begin

                weight[1][63:32] = tr.wdata;

                w1_hi_valid = 1'b1;

                `uvm_info(
                    "TPU_WRITE",
                    $sformatf(
                        "W1_HI = 0x%08h",
                        tr.wdata
                    ),
                    UVM_MEDIUM
                )

            end


            // =================================================================
            // W2
            // =================================================================

            TPU_W2_LO: begin

                weight[2][31:0] = tr.wdata;

                w2_lo_valid = 1'b1;

                `uvm_info(
                    "TPU_WRITE",
                    $sformatf(
                        "W2_LO = 0x%08h",
                        tr.wdata
                    ),
                    UVM_MEDIUM
                )

            end


            TPU_W2_HI: begin

                weight[2][63:32] = tr.wdata;

                w2_hi_valid = 1'b1;

                `uvm_info(
                    "TPU_WRITE",
                    $sformatf(
                        "W2_HI = 0x%08h",
                        tr.wdata
                    ),
                    UVM_MEDIUM
                )

            end


            // =================================================================
            // W3
            // =================================================================

            TPU_W3_LO: begin

                weight[3][31:0] = tr.wdata;

                w3_lo_valid = 1'b1;

                `uvm_info(
                    "TPU_WRITE",
                    $sformatf(
                        "W3_LO = 0x%08h",
                        tr.wdata
                    ),
                    UVM_MEDIUM
                )

            end


            TPU_W3_HI: begin

                weight[3][63:32] = tr.wdata;

                w3_hi_valid = 1'b1;

                `uvm_info(
                    "TPU_WRITE",
                    $sformatf(
                        "W3_HI = 0x%08h",
                        tr.wdata
                    ),
                    UVM_MEDIUM
                )

            end


            // =================================================================
            // W4
            // =================================================================

            TPU_W4_LO: begin

                weight[4][31:0] = tr.wdata;

                w4_lo_valid = 1'b1;

                `uvm_info(
                    "TPU_WRITE",
                    $sformatf(
                        "W4_LO = 0x%08h",
                        tr.wdata
                    ),
                    UVM_MEDIUM
                )

            end


            TPU_W4_HI: begin

                weight[4][63:32] = tr.wdata;

                w4_hi_valid = 1'b1;

                `uvm_info(
                    "TPU_WRITE",
                    $sformatf(
                        "W4_HI = 0x%08h",
                        tr.wdata
                    ),
                    UVM_MEDIUM
                )

            end


            // =================================================================
            // INPUT0
            // =================================================================

            TPU_INPUT0_LO: begin

                input0[31:0] = tr.wdata;

                input0_lo_valid = 1'b1;

                `uvm_info(
                    "TPU_WRITE",
                    $sformatf(
                        "INPUT0_LO = 0x%08h",
                        tr.wdata
                    ),
                    UVM_MEDIUM
                )

            end


            TPU_INPUT0_HI: begin

                input0[63:32] = tr.wdata;

                input0_hi_valid = 1'b1;

                `uvm_info(
                    "TPU_WRITE",
                    $sformatf(
                        "INPUT0_HI = 0x%08h",
                        tr.wdata
                    ),
                    UVM_MEDIUM
                )

            end


            // =================================================================
            // INPUT1
            // =================================================================

            TPU_INPUT1_LO: begin

                input1[31:0] = tr.wdata;

                input1_lo_valid = 1'b1;

                `uvm_info(
                    "TPU_WRITE",
                    $sformatf(
                        "INPUT1_LO = 0x%08h",
                        tr.wdata
                    ),
                    UVM_MEDIUM
                )

            end


            TPU_INPUT1_HI: begin

                input1[63:32] = tr.wdata;

                input1_hi_valid = 1'b1;

                `uvm_info(
                    "TPU_WRITE",
                    $sformatf(
                        "INPUT1_HI = 0x%08h",
                        tr.wdata
                    ),
                    UVM_MEDIUM
                )

            end


            // =================================================================
            // CONTROL
            // =================================================================

            TPU_CONTROL: begin

                // START is bit zero.

                if (tr.wdata[0]) begin

                    start_count++;
                    start_seen = 1'b1;

                    `uvm_info(
                        "TPU_START",
                        "TPU START detected",
                        UVM_MEDIUM
                    )


                    // ---------------------------------------------------------
                    // Verify that all operands were supplied before START.
                    // ---------------------------------------------------------

                    if (!all_operands_valid()) begin

                        `uvm_error(
                            "TPU_START",
                            "TPU START detected before all 64-bit weights/input operands were written"
                        )

                    end
                    else begin

                        // -----------------------------------------------------
                        // Run the functional reference model.
                        // -----------------------------------------------------

                        run_reference_model();

                    end

                end

            end


            // =================================================================
            // Unknown TPU write
            // =================================================================

            default: begin

                `uvm_info(
                    "TPU_WRITE",
                    $sformatf(
                        "Unrecognized TPU write: addr=0x%08h data=0x%08h",
                        tr.addr,
                        tr.wdata
                    ),
                    UVM_LOW
                )

            end

        endcase

    endfunction


    // =========================================================================
    // Process TPU read
    // =========================================================================
    //
    // Reads are used to verify:
    //
    //     STATUS
    //     RESULT0
    //     RESULT1
    //
    // The scoreboard compares the actual CPU-visible data against the expected
    // result produced by the reference model.
    //
    // =========================================================================

    virtual function void process_tpu_read(soc_sequence_item tr);

        case (tr.addr)

            // =================================================================
            // STATUS
            // =================================================================

            TPU_STATUS: begin

                check_status(tr);

            end


            // =================================================================
            // RESULT0 low word
            // =================================================================

            TPU_RESULT0_LO: begin

                if (reference_model_valid) begin

                    compare_result_word(
                        "RESULT0_LO",
                        expected_result0[31:0],
                        tr.rdata,
                        tr.addr
                    );

                    result0_lo_checked = 1'b1;

                end
                else begin

                    `uvm_warning(
                        "TPU_RESULT",
                        "RESULT0_LO read observed before reference model generated an expected result"
                    )

                end

            end


            // =================================================================
            // RESULT0 high word
            // =================================================================

            TPU_RESULT0_HI: begin

                if (reference_model_valid) begin

                    compare_result_word(
                        "RESULT0_HI",
                        expected_result0[63:32],
                        tr.rdata,
                        tr.addr
                    );

                    result0_hi_checked = 1'b1;

                end
                else begin

                    `uvm_warning(
                        "TPU_RESULT",
                        "RESULT0_HI read observed before reference model generated an expected result"
                    )

                end

            end


            // =================================================================
            // RESULT1 low word
            // =================================================================

            TPU_RESULT1_LO: begin

                if (reference_model_valid) begin

                    compare_result_word(
                        "RESULT1_LO",
                        expected_result1[31:0],
                        tr.rdata,
                        tr.addr
                    );

                    result1_lo_checked = 1'b1;

                end
                else begin

                    `uvm_warning(
                        "TPU_RESULT",
                        "RESULT1_LO read observed before reference model generated an expected result"
                    )

                end

            end


            // =================================================================
            // RESULT1 high word
            // =================================================================

            TPU_RESULT1_HI: begin

                if (reference_model_valid) begin

                    compare_result_word(
                        "RESULT1_HI",
                        expected_result1[63:32],
                        tr.rdata,
                        tr.addr
                    );

                    result1_hi_checked = 1'b1;

                end
                else begin

                    `uvm_warning(
                        "TPU_RESULT",
                        "RESULT1_HI read observed before reference model generated an expected result"
                    )

                end

            end


            // =================================================================
            // Other TPU read
            // =================================================================

            default: begin

                `uvm_info(
                    "TPU_READ",
                    $sformatf(
                        "Unrecognized TPU read: addr=0x%08h rdata=0x%08h",
                        tr.addr,
                        tr.rdata
                    ),
                    UVM_LOW
                )

            end

        endcase

    endfunction


    // =========================================================================
    // Check STATUS register
    // =========================================================================
    //
    // STATUS:
    //
    //     bit 0 = BUSY
    //     bit 1 = DONE
    //
    // The exact cycle-level BUSY/DONE timing should ultimately be derived from
    // the RTL. Therefore this scoreboard performs conservative checks:
    //
    //     - reserved bits are expected to be zero
    //     - before START, DONE should not spontaneously indicate completion
    //
    // Detailed cycle-accurate timing can be added once the final TPU controller
    // latency is fixed.
    //
    // =========================================================================

    virtual function void check_status(soc_sequence_item tr);

        bit busy;
        bit done;

        busy = tr.rdata[0];
        done = tr.rdata[1];


        // ---------------------------------------------------------------------
        // Reserved bits
        // ---------------------------------------------------------------------

        if (tr.rdata[31:2] != 30'b0) begin

            `uvm_error(
                "TPU_STATUS",
                $sformatf(
                    "STATUS reserved bits are non-zero: rdata=0x%08h",
                    tr.rdata
                )
            )

        end


        // ---------------------------------------------------------------------
        // Informational reporting
        // ---------------------------------------------------------------------

        `uvm_info(
            "TPU_STATUS",
            $sformatf(
                "STATUS read: BUSY=%0b DONE=%0b",
                busy,
                done
            ),
            UVM_MEDIUM
        )


        // ---------------------------------------------------------------------
        // If the reference model has completed, a DONE result should normally
        // become observable before result reads.
        //
        // We deliberately do not impose a fixed cycle count here because the
        // final controller timing should come from the RTL.
        // ---------------------------------------------------------------------

        if (reference_model_valid && !done) begin

            `uvm_info(
                "TPU_STATUS",
                "Reference model has completed; RTL STATUS does not yet report DONE",
                UVM_LOW
            )

        end

    endfunction


    // =========================================================================
    // Verify all operands have been captured
    // =========================================================================

    virtual function bit all_operands_valid();

        return
            w0_lo_valid &&
            w0_hi_valid &&

            w1_lo_valid &&
            w1_hi_valid &&

            w2_lo_valid &&
            w2_hi_valid &&

            w3_lo_valid &&
            w3_hi_valid &&

            w4_lo_valid &&
            w4_hi_valid &&

            input0_lo_valid &&
            input0_hi_valid &&

            input1_lo_valid &&
            input1_hi_valid;

    endfunction


    // =========================================================================
    // Run functional reference model
    // =========================================================================
    //
    // The reference model receives the complete 64-bit software-visible
    // operands.
    //
    // The model is responsible for:
    //
    //     - unpacking signed 16-bit lanes
    //     - exact PE fixed-point arithmetic
    //     - 16-bit wraparound
    //     - exact RTL-derived weight mapping
    //     - sigmoid Q5.10 addressing
    //     - exact 256-entry LUT
    //     - exact result packing
    //
    // The scoreboard itself should not duplicate those numerical operations.
    //
    // =========================================================================

    virtual function void run_reference_model();

        `uvm_info(
            "TPU_REF",
            "Running TPU functional reference model",
            UVM_MEDIUM
        )


        // ---------------------------------------------------------------------
        // Send all captured operands to the reference model.
        // ---------------------------------------------------------------------

        tpu_ref_set_weight(0, weight[0]);
        tpu_ref_set_weight(1, weight[1]);
        tpu_ref_set_weight(2, weight[2]);
        tpu_ref_set_weight(3, weight[3]);
        tpu_ref_set_weight(4, weight[4]);

        tpu_ref_set_input(0, input0);
        tpu_ref_set_input(1, input1);


        // ---------------------------------------------------------------------
        // Execute the functional model.
        // ---------------------------------------------------------------------

        tpu_ref_start();


        // ---------------------------------------------------------------------
        // Retrieve expected results.
        // ---------------------------------------------------------------------

        expected_result0 = tpu_ref_get_result(0);
        expected_result1 = tpu_ref_get_result(1);


        reference_model_valid = 1'b1;


        `uvm_info(
            "TPU_REF",
            $sformatf(
                "Expected RESULT0 = 0x%016h, RESULT1 = 0x%016h",
                expected_result0,
                expected_result1
            ),
            UVM_MEDIUM
        )

    endfunction


    // =========================================================================
    // Compare one 32-bit result word
    // =========================================================================

    virtual function void compare_result_word(
        string       result_name,
        bit [31:0]   expected,
        bit [31:0]   actual,
        bit [31:0]   addr
    );

        result_compare_count++;


        if (actual === expected) begin

            `uvm_info(
                "TPU_PASS",
                $sformatf(
                    "%s PASS: addr=0x%08h expected=0x%08h actual=0x%08h",
                    result_name,
                    addr,
                    expected,
                    actual
                ),
                UVM_LOW
            )

        end
        else begin

            result_error_count++;

            `uvm_error(
                "TPU_FAIL",
                $sformatf(
                    "%s MISMATCH: addr=0x%08h expected=0x%08h actual=0x%08h",
                    result_name,
                    addr,
                    expected,
                    actual
                )
            )

        end

    endfunction


    // =========================================================================
    // Clear operand capture state
    // =========================================================================
    //
    // Called at construction and can also be used when starting a new TPU
    // transaction sequence.
    //
    // =========================================================================

    virtual function void clear_capture_state();

        weight[0] = '0;
        weight[1] = '0;
        weight[2] = '0;
        weight[3] = '0;
        weight[4] = '0;

        input0 = '0;
        input1 = '0;

        w0_lo_valid = 1'b0;
        w0_hi_valid = 1'b0;

        w1_lo_valid = 1'b0;
        w1_hi_valid = 1'b0;

        w2_lo_valid = 1'b0;
        w2_hi_valid = 1'b0;

        w3_lo_valid = 1'b0;
        w3_hi_valid = 1'b0;

        w4_lo_valid = 1'b0;
        w4_hi_valid = 1'b0;

        input0_lo_valid = 1'b0;
        input0_hi_valid = 1'b0;

        input1_lo_valid = 1'b0;
        input1_hi_valid = 1'b0;

        expected_result0 = '0;
        expected_result1 = '0;

        reference_model_valid = 1'b0;

        start_seen = 1'b0;

        result0_lo_checked = 1'b0;
        result0_hi_checked = 1'b0;

        result1_lo_checked = 1'b0;
        result1_hi_checked = 1'b0;

    endfunction


    // =========================================================================
    // Report phase
    // =========================================================================
    //
    // Provides a concise end-of-test summary suitable for regression logs.
    //
    // =========================================================================

    virtual function void report_phase(uvm_phase phase);

        super.report_phase(phase);


        `uvm_info(
            "TPU_SCB_SUMMARY",
            "============================================================",
            UVM_NONE
        )

        `uvm_info(
            "TPU_SCB_SUMMARY",
            $sformatf(
                "TPU write transactions : %0d",
                tpu_write_count
            ),
            UVM_NONE
        )

        `uvm_info(
            "TPU_SCB_SUMMARY",
            $sformatf(
                "TPU read transactions  : %0d",
                tpu_read_count
            ),
            UVM_NONE
        )

        `uvm_info(
            "TPU_SCB_SUMMARY",
            $sformatf(
                "TPU START events       : %0d",
                start_count
            ),
            UVM_NONE
        )

        `uvm_info(
            "TPU_SCB_SUMMARY",
            $sformatf(
                "Result comparisons     : %0d",
                result_compare_count
            ),
            UVM_NONE
        )

        `uvm_info(
            "TPU_SCB_SUMMARY",
            $sformatf(
                "Result mismatches      : %0d",
                result_error_count
            ),
            UVM_NONE
        )

        `uvm_info(
            "TPU_SCB_SUMMARY",
            "============================================================",
            UVM_NONE
        )


        if (result_error_count == 0 &&
            result_compare_count != 0) begin

            `uvm_info(
                "TPU_SCB_SUMMARY",
                "TPU SCOREBOARD: ALL RESULT CHECKS PASSED",
                UVM_NONE
            )

        end
        else if (result_error_count != 0) begin

            `uvm_error(
                "TPU_SCB_SUMMARY",
                $sformatf(
                    "TPU SCOREBOARD: %0d RESULT MISMATCH(ES)",
                    result_error_count
                )
            )

        end
        else begin

            `uvm_warning(
                "TPU_SCB_SUMMARY",
                "TPU scoreboard completed without result comparisons"
            )

        end

    endfunction


endclass


// =============================================================================
// DPI-C REFERENCE MODEL INTERFACE
// =============================================================================
//
// These declarations represent the bridge between SystemVerilog/UVM and the
// C golden reference model.
//
// If your C model is compiled through Questa DPI-C, the corresponding C
// functions must use compatible DPI types.
//
// NOTE:
// The exact function names can be changed to match your final
// tpu_ref_model.c implementation.
//
// =============================================================================

import "DPI-C" function void tpu_ref_set_weight(
    input int unsigned index,
    input longint unsigned value
);

import "DPI-C" function void tpu_ref_set_input(
    input int unsigned index,
    input longint unsigned value
);

import "DPI-C" function void tpu_ref_start();

import "DPI-C" function longint unsigned tpu_ref_get_result(
    input int unsigned index
);


`endif
